# Generated by Django 4.0.2 on 2022-05-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50, verbose_name='Pseudo')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Prénom')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nom')),
                ('avatar', models.ImageField(blank=True, default='giphy_python.gif', null=True, upload_to='avatar/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
