# Generated by Django 4.0.2 on 2022-03-23 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Couleur du leurre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_lure')),
            ],
        ),
        migrations.CreateModel(
            name='Lure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Leurre')),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CatchFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sky_state', models.CharField(choices=[('Ensoleillé', 'Ensoleillé'), ('Blanc', 'Blanc'), ('Gris', 'Gris'), ('Noir', 'Noir')], default='Ensoleillé', max_length=30, verbose_name='Etat du ciel')),
                ('water_state', models.CharField(choices=[('Clair', 'Clair'), ('Trouble', 'Trouble')], default='Clair', max_length=30, verbose_name="Etat de l'eau")),
                ('color_lure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adddata.color', verbose_name='Couleur du leurre')),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pécheur')),
                ('lure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adddata.lure', verbose_name='Leurre')),
            ],
        ),
    ]
