name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Flake8 and Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Flake8
      run: |
        flake8 . --exclude env,__init__.py,migrations --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Tests
      run: |
        python manage.py test
